ACTION={
	NONE         = 0,
	STAND        = 1,
	WALK         = 2,
	RUN          = 3,
	ATTACK       = 4,
 	CAST_SKILL   = 5,
	DASH         = 6,
	DASH_BACK    = 7,
	HIT          = 8,
	HIT_BACK     = 9,
	ATTACK_READY = 10
}
EVENT={
	SCENE_INIT 		    = "SCENE_INIT",
	SCENE_BEGIN_FRAME 	= "SCENE_BEGIN_FRAME",
	SCENE_FRAME 	    = "SCENE_FRAME",
	SCENE_DESTROY	    = "SCENE_DESTROY",

	HUMAN_ENTER_SCENE   = "HUMAN_ENTER_SCENE",
	HUMAN_EXIT_SCENE    = "HUMAN_EXIT_SCENE",

	COLLECT_ENTER_SCENE = "COLLECT_ENTER_SCENE",
	COLLECT_EXIT_SCENE  = "COLLECT_EXIT_SCENE",

	MONSTER_ENTER_SCENE = "MONSTER_ENTER_SCENE",
	MONSTER_EXIT_SCENE  = "MONSTER_EXIT_SCENE",

	DROP_ENTER_SCENE    = "DROP_ENTER_SCENE",
	DROP_EXIT_SCENE     = "DROP_EXIT_SCENE",

	MAGIC_ENTER_SCENE   = "MAGIC_ENTER_SCENE",
	MAGIC_EXIT_SCENE    = "MAGIC_EXIT_SCENE",

	TOMB_ENTER_SCENE    = "TOMB_ENTER_SCENE",
	TOMB_EXIT_SCENE     = "TOMB_EXIT_SCENE",

	HUMAN_FRAME 	    = "HUMAN_FRAME",
	MONSTER_FRAME 	    = "MONSTER_FRAME",
	MAGIC_FRAME 	    = "MAGIC_FRAME",
	COLLECT_FRAME       = "COLLECT_FRAME",
	DROP_FRAME	        = "DROP_FRAME",
	TOMB_FRAME	        = "TOMB_FRAME",

	OBJ_DIE             = "OBJ_DIE",

	ON_JOYSTICK_MOVE     = "ON_JOYSTICK_MOVE",
	ON_JOYSTICK_MOVE_END = "ON_JOYSTICK_MOVE_END",
	ON_JOYSTICK_BASE_ATK = "ON_JOYSTICK_BASE_ATK",
	ON_JOYSTICK_SKILL_1  = "ON_JOYSTICK_SKILL_1",
	ON_JOYSTICK_SKILL_2  = "ON_JOYSTICK_SKILL_2",
	ON_JOYSTICK_SKILL_3  = "ON_JOYSTICK_SKILL_3",
	ON_JOYSTICK_SKILL_4  = "ON_JOYSTICK_SKILL_4",

}