//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MainManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MainManager), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("OnFixedUpdateCallback", OnFixedUpdateCallback);
		L.RegFunction("OnUpdateCallback", OnUpdateCallback);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnFixedUpdateCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MainManager obj = (MainManager)ToLua.CheckObject<MainManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnFixedUpdateCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnUpdateCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MainManager obj = (MainManager)ToLua.CheckObject<MainManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.OnUpdateCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

